# This Makefile was generated by Mesa v2.1
# Generation Date: 1722788631
# DO NOT EDIT THIS FILE AS IT WILL BE RE-GENERATED

################### VARIABLES ###################

COLOR_RED := $(shell echo -e "\033[31m")
COLOR_GREEN := $(shell echo -e "\033[33m")
COLOR_BLUE := $(shell echo -e "\033[34m")
COLOR_CYAN := $(shell echo -e "\033[36m")
COLOR_NORM := $(shell echo -e "\033[0\;39m")

STYLE_ITALIC := $(shell echo -e "\033[3m")
STYLE_ULINE := $(shell echo -e "\033[4m")
STYLE_NORM := $(shell echo -e "\033[0m")
CXX := /usr/bin/clang++
I_CPPFLAGS := -DMESA_BUILD
BIN_DIR := bin
OBJ_DIR := $(BIN_DIR)/objs
Wildcat_Usermode_Driver_INCDIRS := $(wildcard ./*.h) $(wildcard ./*.hpp) $(wildcard vendor/SDL/include/*.h) $(wildcard vendor/SDL/include/*.hpp) 
Wildcat_Usermode_Driver_CPPFLAGS := -DNDEBUG=true -I. -Ivendor/SDL/include  -O3 -g -std=c++17
Wildcat_Usermode_Driver_LDFLAGS := -L$(BIN_DIR) 
Wildcat_Usermode_Driver_STATIC_LIBS := 
Wildcat_Usermode_Driver_DYN_LIBS := $(BIN_DIR)/libSDL2-2.0.so.0.3100.0 
Wildcat_Main_INCDIRS := $(wildcard ./*.h) $(wildcard ./*.hpp) $(wildcard vendor/iconfont/*.h) $(wildcard vendor/iconfont/*.hpp) $(wildcard vendor/SDL/include /*.h) $(wildcard vendor/SDL/include /*.hpp) $(wildcard vendor/imgui/*.h) $(wildcard vendor/imgui/*.hpp) 
Wildcat_Main_CPPFLAGS := -DNDEBUG=true -I. -Ivendor/iconfont -Ivendor/SDL/include  -Ivendor/imgui  -O3 -g -std=c++17
Wildcat_Main_LDFLAGS := -L$(BIN_DIR) 
Wildcat_Main_STATIC_LIBS := 
Wildcat_Main_DYN_LIBS := $(BIN_DIR)/libSDL2-2.0.so.0.3100.0 

################### PROJECTS ###################

all: Wildcat_Usermode_Driver Wildcat_Main 

clean:
	@echo $(COLOR_BLUE)[RM]$(COLOR_NORM) Purging contents of $(STYLE_ULINE)$(BIN_DIR)/objs/$(STYLE_NORM)
	@rm -rf $(BIN_DIR)/objs/*

Prep:
	@echo $(COLOR_BLUE)[MKDIR]$(COLOR_NORM) Creating $(STYLE_ULINE)$(OBJ_DIR)$(STYLE_NORM)
	@mkdir -p $(OBJ_DIR)
	@mkdir -p $(OBJ_DIR)/Wildcat_Usermode_Driver
	@mkdir -p $(OBJ_DIR)/Wildcat_Main

projects:
	@echo "### Project List ###"
	@echo "	* [EXE] 'Wildcat Usermode Driver' > $(BIN_DIR)/wildcatuserdriver"
	@echo "	* [EXE] 'Wildcat Main' > $(BIN_DIR)/wildcat"

$(OBJ_DIR)/Wildcat_Usermode_Driver/main_driver.cpp.o: main_driver.cpp $(Wildcat_Usermode_Driver_INCDIRS)
	@echo $(COLOR_BLUE)[CXX]$(COLOR_NORM) main_driver.cpp
	@$(CXX) $(CPPFLAGS) $(Wildcat_Usermode_Driver_CPPFLAGS) $(I_CPPFLAGS) -c main_driver.cpp -o $(OBJ_DIR)/Wildcat_Usermode_Driver/main_driver.cpp.o

$(OBJ_DIR)/Wildcat_Usermode_Driver/wildcatuserdriver.cpp.o: wildcatuserdriver.cpp $(Wildcat_Usermode_Driver_INCDIRS)
	@echo $(COLOR_BLUE)[CXX]$(COLOR_NORM) wildcatuserdriver.cpp
	@$(CXX) $(CPPFLAGS) $(Wildcat_Usermode_Driver_CPPFLAGS) $(I_CPPFLAGS) -c wildcatuserdriver.cpp -o $(OBJ_DIR)/Wildcat_Usermode_Driver/wildcatuserdriver.cpp.o

Wildcat_Usermode_Driver: Prep $(OBJ_DIR)/Wildcat_Usermode_Driver/main_driver.cpp.o $(OBJ_DIR)/Wildcat_Usermode_Driver/wildcatuserdriver.cpp.o 
	@echo $(COLOR_GREEN)[EXE]$(COLOR_NORM) Linking Wildcat Usermode Driver \> $(STYLE_ULINE)$(BIN_DIR)/wildcatuserdriver$(STYLE_NORM)
	@$(CXX) -o $(BIN_DIR)/wildcatuserdriver $(OBJ_DIR)/Wildcat_Usermode_Driver/main_driver.cpp.o $(OBJ_DIR)/Wildcat_Usermode_Driver/wildcatuserdriver.cpp.o  $(Wildcat_Usermode_Driver_LDFLAGS) $(Wildcat_Usermode_Driver_STATIC_LIBS) -Wl,-rpath $(BIN_DIR) $(Wildcat_Usermode_Driver_DYN_LIBS)

$(OBJ_DIR)/Wildcat_Main/main.cpp.o: main.cpp $(Wildcat_Main_INCDIRS)
	@echo $(COLOR_BLUE)[CXX]$(COLOR_NORM) main.cpp
	@$(CXX) $(CPPFLAGS) $(Wildcat_Main_CPPFLAGS) $(I_CPPFLAGS) -c main.cpp -o $(OBJ_DIR)/Wildcat_Main/main.cpp.o

$(OBJ_DIR)/Wildcat_Main/wildcatmainwindow.cpp.o: wildcatmainwindow.cpp $(Wildcat_Main_INCDIRS)
	@echo $(COLOR_BLUE)[CXX]$(COLOR_NORM) wildcatmainwindow.cpp
	@$(CXX) $(CPPFLAGS) $(Wildcat_Main_CPPFLAGS) $(I_CPPFLAGS) -c wildcatmainwindow.cpp -o $(OBJ_DIR)/Wildcat_Main/wildcatmainwindow.cpp.o

$(OBJ_DIR)/Wildcat_Main/wildcatchannel.cpp.o: wildcatchannel.cpp $(Wildcat_Main_INCDIRS)
	@echo $(COLOR_BLUE)[CXX]$(COLOR_NORM) wildcatchannel.cpp
	@$(CXX) $(CPPFLAGS) $(Wildcat_Main_CPPFLAGS) $(I_CPPFLAGS) -c wildcatchannel.cpp -o $(OBJ_DIR)/Wildcat_Main/wildcatchannel.cpp.o

$(OBJ_DIR)/Wildcat_Main/wildcatuserdriver.cpp.o: wildcatuserdriver.cpp $(Wildcat_Main_INCDIRS)
	@echo $(COLOR_BLUE)[CXX]$(COLOR_NORM) wildcatuserdriver.cpp
	@$(CXX) $(CPPFLAGS) $(Wildcat_Main_CPPFLAGS) $(I_CPPFLAGS) -c wildcatuserdriver.cpp -o $(OBJ_DIR)/Wildcat_Main/wildcatuserdriver.cpp.o

$(OBJ_DIR)/Wildcat_Main/wildcatauth.cpp.o: wildcatauth.cpp $(Wildcat_Main_INCDIRS)
	@echo $(COLOR_BLUE)[CXX]$(COLOR_NORM) wildcatauth.cpp
	@$(CXX) $(CPPFLAGS) $(Wildcat_Main_CPPFLAGS) $(I_CPPFLAGS) -c wildcatauth.cpp -o $(OBJ_DIR)/Wildcat_Main/wildcatauth.cpp.o

$(OBJ_DIR)/Wildcat_Main/wildcatdevice.cpp.o: wildcatdevice.cpp $(Wildcat_Main_INCDIRS)
	@echo $(COLOR_BLUE)[CXX]$(COLOR_NORM) wildcatdevice.cpp
	@$(CXX) $(CPPFLAGS) $(Wildcat_Main_CPPFLAGS) $(I_CPPFLAGS) -c wildcatdevice.cpp -o $(OBJ_DIR)/Wildcat_Main/wildcatdevice.cpp.o

$(OBJ_DIR)/Wildcat_Main/wildcatsavefile.cpp.o: wildcatsavefile.cpp $(Wildcat_Main_INCDIRS)
	@echo $(COLOR_BLUE)[CXX]$(COLOR_NORM) wildcatsavefile.cpp
	@$(CXX) $(CPPFLAGS) $(Wildcat_Main_CPPFLAGS) $(I_CPPFLAGS) -c wildcatsavefile.cpp -o $(OBJ_DIR)/Wildcat_Main/wildcatsavefile.cpp.o

$(OBJ_DIR)/Wildcat_Main/wildcatsettingswindow.cpp.o: wildcatsettingswindow.cpp $(Wildcat_Main_INCDIRS)
	@echo $(COLOR_BLUE)[CXX]$(COLOR_NORM) wildcatsettingswindow.cpp
	@$(CXX) $(CPPFLAGS) $(Wildcat_Main_CPPFLAGS) $(I_CPPFLAGS) -c wildcatsettingswindow.cpp -o $(OBJ_DIR)/Wildcat_Main/wildcatsettingswindow.cpp.o

$(OBJ_DIR)/Wildcat_Main/wildcataboutwindow.cpp.o: wildcataboutwindow.cpp $(Wildcat_Main_INCDIRS)
	@echo $(COLOR_BLUE)[CXX]$(COLOR_NORM) wildcataboutwindow.cpp
	@$(CXX) $(CPPFLAGS) $(Wildcat_Main_CPPFLAGS) $(I_CPPFLAGS) -c wildcataboutwindow.cpp -o $(OBJ_DIR)/Wildcat_Main/wildcataboutwindow.cpp.o

$(OBJ_DIR)/Wildcat_Main/vendor_imgui_backends_imgui_impl_sdl2.cpp.o: vendor/imgui/backends/imgui_impl_sdl2.cpp $(Wildcat_Main_INCDIRS)
	@echo $(COLOR_BLUE)[CXX]$(COLOR_NORM) vendor/imgui/backends/imgui_impl_sdl2.cpp
	@$(CXX) $(CPPFLAGS) $(Wildcat_Main_CPPFLAGS) $(I_CPPFLAGS) -c vendor/imgui/backends/imgui_impl_sdl2.cpp -o $(OBJ_DIR)/Wildcat_Main/vendor_imgui_backends_imgui_impl_sdl2.cpp.o

$(OBJ_DIR)/Wildcat_Main/vendor_imgui_backends_imgui_impl_sdlrenderer2.cpp.o: vendor/imgui/backends/imgui_impl_sdlrenderer2.cpp $(Wildcat_Main_INCDIRS)
	@echo $(COLOR_BLUE)[CXX]$(COLOR_NORM) vendor/imgui/backends/imgui_impl_sdlrenderer2.cpp
	@$(CXX) $(CPPFLAGS) $(Wildcat_Main_CPPFLAGS) $(I_CPPFLAGS) -c vendor/imgui/backends/imgui_impl_sdlrenderer2.cpp -o $(OBJ_DIR)/Wildcat_Main/vendor_imgui_backends_imgui_impl_sdlrenderer2.cpp.o

$(OBJ_DIR)/Wildcat_Main/vendor_imgui_imgui.cpp.o: vendor/imgui/imgui.cpp $(Wildcat_Main_INCDIRS)
	@echo $(COLOR_BLUE)[CXX]$(COLOR_NORM) vendor/imgui/imgui.cpp
	@$(CXX) $(CPPFLAGS) $(Wildcat_Main_CPPFLAGS) $(I_CPPFLAGS) -c vendor/imgui/imgui.cpp -o $(OBJ_DIR)/Wildcat_Main/vendor_imgui_imgui.cpp.o

$(OBJ_DIR)/Wildcat_Main/vendor_imgui_imgui_widgets.cpp.o: vendor/imgui/imgui_widgets.cpp $(Wildcat_Main_INCDIRS)
	@echo $(COLOR_BLUE)[CXX]$(COLOR_NORM) vendor/imgui/imgui_widgets.cpp
	@$(CXX) $(CPPFLAGS) $(Wildcat_Main_CPPFLAGS) $(I_CPPFLAGS) -c vendor/imgui/imgui_widgets.cpp -o $(OBJ_DIR)/Wildcat_Main/vendor_imgui_imgui_widgets.cpp.o

$(OBJ_DIR)/Wildcat_Main/vendor_imgui_imgui_demo.cpp.o: vendor/imgui/imgui_demo.cpp $(Wildcat_Main_INCDIRS)
	@echo $(COLOR_BLUE)[CXX]$(COLOR_NORM) vendor/imgui/imgui_demo.cpp
	@$(CXX) $(CPPFLAGS) $(Wildcat_Main_CPPFLAGS) $(I_CPPFLAGS) -c vendor/imgui/imgui_demo.cpp -o $(OBJ_DIR)/Wildcat_Main/vendor_imgui_imgui_demo.cpp.o

$(OBJ_DIR)/Wildcat_Main/vendor_imgui_imgui_tables.cpp.o: vendor/imgui/imgui_tables.cpp $(Wildcat_Main_INCDIRS)
	@echo $(COLOR_BLUE)[CXX]$(COLOR_NORM) vendor/imgui/imgui_tables.cpp
	@$(CXX) $(CPPFLAGS) $(Wildcat_Main_CPPFLAGS) $(I_CPPFLAGS) -c vendor/imgui/imgui_tables.cpp -o $(OBJ_DIR)/Wildcat_Main/vendor_imgui_imgui_tables.cpp.o

$(OBJ_DIR)/Wildcat_Main/vendor_imgui_imgui_draw.cpp.o: vendor/imgui/imgui_draw.cpp $(Wildcat_Main_INCDIRS)
	@echo $(COLOR_BLUE)[CXX]$(COLOR_NORM) vendor/imgui/imgui_draw.cpp
	@$(CXX) $(CPPFLAGS) $(Wildcat_Main_CPPFLAGS) $(I_CPPFLAGS) -c vendor/imgui/imgui_draw.cpp -o $(OBJ_DIR)/Wildcat_Main/vendor_imgui_imgui_draw.cpp.o

$(OBJ_DIR)/Wildcat_Main/vendor_imgui_misc_cpp_imgui_stdlib.cpp.o: vendor/imgui/misc/cpp/imgui_stdlib.cpp $(Wildcat_Main_INCDIRS)
	@echo $(COLOR_BLUE)[CXX]$(COLOR_NORM) vendor/imgui/misc/cpp/imgui_stdlib.cpp
	@$(CXX) $(CPPFLAGS) $(Wildcat_Main_CPPFLAGS) $(I_CPPFLAGS) -c vendor/imgui/misc/cpp/imgui_stdlib.cpp -o $(OBJ_DIR)/Wildcat_Main/vendor_imgui_misc_cpp_imgui_stdlib.cpp.o

Wildcat_Main: Prep $(OBJ_DIR)/Wildcat_Main/main.cpp.o $(OBJ_DIR)/Wildcat_Main/wildcatmainwindow.cpp.o $(OBJ_DIR)/Wildcat_Main/wildcatchannel.cpp.o $(OBJ_DIR)/Wildcat_Main/wildcatuserdriver.cpp.o $(OBJ_DIR)/Wildcat_Main/wildcatauth.cpp.o $(OBJ_DIR)/Wildcat_Main/wildcatdevice.cpp.o $(OBJ_DIR)/Wildcat_Main/wildcatsavefile.cpp.o $(OBJ_DIR)/Wildcat_Main/wildcatsettingswindow.cpp.o $(OBJ_DIR)/Wildcat_Main/wildcataboutwindow.cpp.o $(OBJ_DIR)/Wildcat_Main/vendor_imgui_backends_imgui_impl_sdl2.cpp.o $(OBJ_DIR)/Wildcat_Main/vendor_imgui_backends_imgui_impl_sdlrenderer2.cpp.o $(OBJ_DIR)/Wildcat_Main/vendor_imgui_imgui.cpp.o $(OBJ_DIR)/Wildcat_Main/vendor_imgui_imgui_widgets.cpp.o $(OBJ_DIR)/Wildcat_Main/vendor_imgui_imgui_demo.cpp.o $(OBJ_DIR)/Wildcat_Main/vendor_imgui_imgui_tables.cpp.o $(OBJ_DIR)/Wildcat_Main/vendor_imgui_imgui_draw.cpp.o $(OBJ_DIR)/Wildcat_Main/vendor_imgui_misc_cpp_imgui_stdlib.cpp.o 
	@echo $(COLOR_GREEN)[EXE]$(COLOR_NORM) Linking Wildcat Main \> $(STYLE_ULINE)$(BIN_DIR)/wildcat$(STYLE_NORM)
	@$(CXX) -o $(BIN_DIR)/wildcat $(OBJ_DIR)/Wildcat_Main/main.cpp.o $(OBJ_DIR)/Wildcat_Main/wildcatmainwindow.cpp.o $(OBJ_DIR)/Wildcat_Main/wildcatchannel.cpp.o $(OBJ_DIR)/Wildcat_Main/wildcatuserdriver.cpp.o $(OBJ_DIR)/Wildcat_Main/wildcatauth.cpp.o $(OBJ_DIR)/Wildcat_Main/wildcatdevice.cpp.o $(OBJ_DIR)/Wildcat_Main/wildcatsavefile.cpp.o $(OBJ_DIR)/Wildcat_Main/wildcatsettingswindow.cpp.o $(OBJ_DIR)/Wildcat_Main/wildcataboutwindow.cpp.o $(OBJ_DIR)/Wildcat_Main/vendor_imgui_backends_imgui_impl_sdl2.cpp.o $(OBJ_DIR)/Wildcat_Main/vendor_imgui_backends_imgui_impl_sdlrenderer2.cpp.o $(OBJ_DIR)/Wildcat_Main/vendor_imgui_imgui.cpp.o $(OBJ_DIR)/Wildcat_Main/vendor_imgui_imgui_widgets.cpp.o $(OBJ_DIR)/Wildcat_Main/vendor_imgui_imgui_demo.cpp.o $(OBJ_DIR)/Wildcat_Main/vendor_imgui_imgui_tables.cpp.o $(OBJ_DIR)/Wildcat_Main/vendor_imgui_imgui_draw.cpp.o $(OBJ_DIR)/Wildcat_Main/vendor_imgui_misc_cpp_imgui_stdlib.cpp.o  $(Wildcat_Main_LDFLAGS) $(Wildcat_Main_STATIC_LIBS) -Wl,-rpath $(BIN_DIR) $(Wildcat_Main_DYN_LIBS)


tasks:
	@echo "### Task List: ###"

.ONESHELL:
compdb:
	make --always-make --dry-run \
	| grep -wE 'clang|clang\+\+' \
	| grep -w '\-c' \
	| jq -nR '[inputs|{directory:".", command:., file: match(" [^ ]+$$").string[1:]}]' > compile_commands.json
.PHONY: clean compdb 
